version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: ant retrieve
          command: ant retrieve
      - run: 
          name: ant push
          command: ant push
         
      - restore_cache:
          keys:
            - pmd-v6.0.1
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.9.0 ]; then
                  curl -L "https://github.com/lovelaureasf/KayakoSFDevSandboxLP/blob/master/pmd-bin-6.9.0.zip" -o pmd-bin-6.9.0.zip
                  unzip pmd-bin-6.9.0.zip
                  rm pmd-bin-6.9.0.zip
              fi
      - save_cache:
          key: pmd-v-6.9.0
          paths:
              - pmd-bin-6.9.0
      - run:
          name: Run Static Analysis
          command: |
              pmd-bin-6.9.0/bin/run.sh pmd -d /home/circleci/project/DirOutput/src -R pmd-bin-6.9.0/Apexruleset.xml -f text -l apex -r static-analysis.txt
      - store_artifacts:
          path: static-analysis.txt
         