version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: ant retrieve
          command: ant retrieve
      - run: 
          name: ant push
          command: ant push
      - run:
          name: Run Static Analysis
          command: |
             chmod u+x pmd-bin-6.9.0/bin/run.sh
             bash pmd-bin-6.9.0/bin/run.sh pmd -d DirOutput/src -R Apexruleset.xml -f text -l apex -r Kayako-analysis.html
      - store_artifacts:
          path: /home/circleci/project/Kayako-analysis.html
         