version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: check Path
          command: echo $PATH
          
      - run:
          name: Add Path
          command: export PATH=$PATH:/sonarqube-6.7.5/bin/linux-x86-64
      - run:
          name: check Path
          command: echo $PATH
          
       - run:
          name: Start Sonar
          command: sonar  
          
      - run: 
          name: ant retrieve
          command: ant retrieve
          
      - run: 
          name: ant push
          command: ant push
         