version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: ant retrieve
          command: ant retrieve
      - run: 
          name: ant push
          command: ant push
         
      - restore_cache:
          keys:
            - pmd-v6.0.1
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.9.0 ]; then
                  curl -L "https://drive.google.com/a/aurea.com/uc?authuser=4&id=1PUCPLsAy1VcSUSCm0qewyb_fY2UQm7Fn&export=download" -o pmd-bin-6.9.0.zip
                  unzip pmd-bin-6.9.0.zip
                  rm pmd-bin-6.9.0.zip
              fi
      - save_cache:
          key: pmd-v-6.9.0
          paths:
              - pmd-bin-6.9.0
      - run:
          name: Run Static Analysis
          command: |
              pmd-bin-6.9.0/bin/run.sh pmd -d DirOutput/src -R Apexruleset.xml -f text -l apex -r Kayako-analysis.html
      - store_artifacts:
          path: /home/circleci/project/static-analysis.html
         