version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: run SonarScanner
          command: mvn sonar:sonar
      - run: 
          name: ant retrieve
          command: ant retrieve
      - run: 
          name: ant push
          command: ant push
         