version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: run SonarScanner
          command: mvn sonar:sonar -Dsonar.organization=lovelaureasf-github -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=7e68eefe869c892f43473456b7768b5b8a8fa0d6
      - run: 
          name: ant retrieve
          command: ant retrieve
      - run: 
          name: ant push
          command: ant push
         